"""Generate DNA HCV report from measured results. Requires reportlab."""
import base64,html,json
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'report';ART=ROOT/'artifacts'/'hcv'
m=json.loads((ART/'metrics.json').read_text());pct=lambda x:f'{100*x:.2f}%'
styles=getSampleStyleSheet()
styles['Normal'].fontSize=10.5;styles['Normal'].leading=15;styles['Normal'].spaceAfter=10
styles['Heading1'].fontSize=21;styles['Heading1'].leading=26;styles['Heading1'].spaceAfter=15
styles['Heading2'].fontSize=12;styles['Heading2'].leading=17;styles['Heading2'].spaceBefore=10;styles['Heading2'].spaceAfter=7
styles.add(ParagraphStyle(name='Cover',fontName='Helvetica-Bold',fontSize=29,leading=35,spaceAfter=18))
styles.add(ParagraphStyle(name='Note',fontSize=9,leading=12,spaceAfter=9,textColor=colors.HexColor('#60746b')))
story=[];web=[]
def p(t,s='Normal'):
    story.append(Paragraph(t,styles[s]));tag={'Cover':'h1','Heading1':'h2','Heading2':'h3'}.get(s,'p');web.append(f'<{tag}>{t}</{tag}>')
def page(title=None):
    if story: story.append(PageBreak());web.append('</section>')
    web.append('<section>')
    if title:p(title,'Heading1')
def table(headers,rows,widths):
    data=[[Paragraph(html.escape(str(c)),styles['Normal']) for c in r] for r in [headers,*rows]]
    t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e9f1ed')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),4),('LINEBELOW',(0,0),(-1,-1),.3,colors.HexColor('#dbe5de'))]));story.extend([t,Spacer(1,12)])
    web.append('<table><tr>'+''.join('<th>'+html.escape(str(c))+'</th>' for c in headers)+'</tr>'+''.join('<tr>'+''.join('<td>'+html.escape(str(c))+'</td>' for c in row)+'</tr>' for row in rows)+'</table>')
def fig(name,w,h,caption):
    path=ART/name;story.append(Image(str(path),width=w,height=h));p(caption,'Note');web.append('<img alt="'+html.escape(caption)+'" src="data:image/png;base64,'+base64.b64encode(path.read_bytes()).decode()+'">')
page()
p('DNA','Cover');p('Disease Diagnosis Using Random Forest','Cover');p('HCV laboratory classification study','Heading2');p('Team DNA | College project report | 6 October 2026','Note')
p('Abstract','Heading2')
p(f'DNA is a working educational application that uses a Random Forest to classify laboratory records into five categories from the official UCI HCV dataset. The experiment uses 492 training records and 123 held-out test records. The evaluated model achieves {pct(m["accuracy"])} accuracy and a macro F1 of {m["macro_f1"]:.3f}. The difference between these metrics reflects a substantial class imbalance and weaker performance on rare categories.')
p('The application combines laboratory input, five class scores, missing-value disclosure, and an Explain and Explore feature. This feature shows how replacing one input with its training median changes the predicted class score and allows comparison of edited input panels. The report covers the method, implementation, measured results, limitations, and a path to adding separate disease modules.')
p('Contents','Heading2')
table(['Section','Page'],[['Problem and dataset','2'],['Methodology','3'],['Implementation and user experience','4'],['Results and evaluation','5'],['Novelty feature','6'],['Limitations and future expansion','7'],['Conclusion and references','8']],[392,76])
p('Educational scope','Heading2');p('DNA predicts research-dataset categories. It does not confirm a diagnosis, recommend treatment, or establish that a blood donor is disease-free.')
page('Problem and dataset')
p('Problem statement','Heading2');p('Build a disease classification model using Random Forest, connect it to an understandable interface, and evaluate how well it distinguishes diagnosis categories from laboratory results. The first module focuses on HCV-related data; broader disease coverage is planned as separate modules after this study is understood.')
p('Dataset selection','Heading2');p('The official UCI HCV dataset contains laboratory and demographic records, with five supplied categories: blood donor, suspected blood donor, hepatitis, fibrosis, and cirrhosis [1]. The local file contains 615 records and 12 predictors. The patient identifier and Category column are excluded from the model inputs.')
table(['Category','Records'],[[k,v] for k,v in m['class_counts'].items()],[350,118])
p('Inputs','Heading2');p('The predictors are age, recorded sex, and ten laboratory fields: ALB, ALP, ALT, AST, BIL, CHE, CHOL, CREA, GGT and PROT. The interface displays their expanded names. UCI does not provide laboratory units in the published variable table [1], so DNA uses original dataset-scale values and supplies research examples. Clinical unit conversions or normal-range flags are not inferred.')
p('Data quality','Heading2');p('Inspection of the downloaded file found missing values in ALB (1), ALP (18), ALT (1), CHOL (10), and PROT (1). Other input columns have no missing entries. The source archive and original CSV are retained. The training outputs record a SHA-256 checksum, class counts, missing counts and row identifiers for reproducibility.')
p('Objectives','Heading2');p('The project demonstrates the complete workflow and lets users inspect input effects. It retains uncommon categories and reports their limitations alongside overall performance.')
page('Methodology')
p('Random Forest','Heading2');p('A Random Forest combines multiple decision trees trained with randomness. Bootstrap samples vary the records seen by each tree, while random feature subsets vary the split candidates. Aggregation reduces dependence on any one tree [2]. The scikit-learn implementation averages class probabilities across trees and selects the highest-scoring class [3].')
table(['Configuration','Value'],[['Trees','400'],['Minimum samples per leaf','2'],['Feature selection at splits','Square root of transformed feature count'],['Class weights','balanced_subsample'],['Random seed','42'],['Tree depth','Unrestricted']],[245,223])
p('Experiment sequence','Heading2');p('1. Load the official CSV and map its five target strings to fixed class identifiers.<br/>2. Make a stratified 80/20 split into 492 training and 123 test records.<br/>3. Run five-fold stratified cross-validation within the training partition.<br/>4. Fit the same pipeline on the complete training partition.<br/>5. Evaluate once on the test records and save that exact model.')
p('Preprocessing and leakage control','Heading2');p('A ColumnTransformer imputes numerical inputs with training medians and one-hot encodes recorded sex. This transformer is inside the pipeline passed to cross-validation, so each fold learns its own medians and category encoding. Test records do not influence preprocessing or fitting. The training script also checks for duplicate feature rows crossing the train/test boundary.')
p('Evaluation design','Heading2');p('The main measures are accuracy, macro F1, balanced accuracy, and per-class precision and recall. Macro F1 gives equal weight to each category. Balanced accuracy averages recall across categories. A most-frequent-class baseline measures how far a classifier can get by always predicting the dominant class. Settings were fixed before evaluation; no test-set tuning or hyperparameter search is performed.')
page('Implementation and user experience')
p('Application architecture','Heading2');p('Training: source CSV to split to preprocessing and Random Forest to model artifacts and evaluation outputs. Inference: laboratory form to validated JSON to the saved pipeline to category scores and explanations. The Flask server runs on the local loopback address.')
table(['Component','Responsibility'],[['modules.py','Defines the HCV input contract and independent artifact location.'],['train.py','Trains the pipeline, evaluates it and exports evidence.'],['app.py','Validates inputs, loads the model and computes predictions and sensitivity.'],['templates and static','DNA branding, responsive layout and client-side interactions.'],['artifacts/hcv','Model, metrics, examples, predictions and charts.'],['test_model.py','Checks data separation, validation, prediction consistency and sensitivity.']],[132,336])
p('DNA interface','Heading2');p('The Lab Explorer separates input, prediction and explanation. Users can load a research sample or enter a panel. Results show every class score, not just the winning label. The evaluation section displays macro F1 alongside accuracy. The layout adapts to narrow screens, labels inputs clearly, and clears stale results when values change.')
p('Input policy','Heading2');p('Age and recorded sex are required. Numerical values must be finite and non-negative, with a broad technical upper bound to avoid numeric overflow. Up to three missing lab values can use training medians; four or more are rejected. This is a demonstration policy, not a validated clinical rule. The output lists all substituted values and flags values beyond observed training ranges.')
p('Run the working model','Heading2');p('From PowerShell in the project folder, run:<br/><font face="Courier">.\\.venv\\Scripts\\python.exe app.py</font><br/>Then visit http://127.0.0.1:5000 and choose Load sample followed by Analyze test panel. Pin the result, edit a lab value, and analyze again to compare. The README includes fresh-install and retraining commands.')
page('Results and evaluation')
table(['Metric','Random Forest','Majority baseline'],[['Accuracy',pct(m['accuracy']),pct(m['baseline_accuracy'])],['Macro F1',f'{m["macro_f1"]:.3f}',f'{m["baseline_macro_f1"]:.3f}'],['Balanced accuracy',pct(m['balanced_accuracy']),'20.00%']],[210,129,129])
table(['Class','Precision','Recall','Test count'],[[n,pct(m['classification_report'][n]['precision']),pct(m['classification_report'][n]['recall']),int(m['classification_report'][n]['support'])] for n in m['labels']],[180,96,96,96])
fig('confusion_matrix.png',300,225,'Figure 1. Actual categories appear in rows and predicted categories in columns.')
p('The model correctly classifies 117 of 123 test records. However, the single suspected-donor test case is missed. Hepatitis recall is 60% on five cases and fibrosis recall is 50% on four cases. These very small groups make estimates unstable. A precision value of zero for a class with no predictions is the reporting convention used here, not a stable estimate of future precision.')
p(f'Five-fold training validation: mean accuracy {pct(m["cv"]["accuracy"]["mean"])} and mean macro F1 {m["cv"]["f1_macro"]["mean"]:.3f}, with macro-F1 standard deviation {m["cv"]["f1_macro"]["std"]:.3f}. Fold variation is descriptive, not a deployment confidence interval.','Note')
page('Novelty feature')
p('Explain and Explore','Heading2');p('The project contribution is an integrated explanation and comparison workflow. After prediction, DNA ranks the observed lab inputs by how strongly replacing each one with its training median changes the current winning category score. This helps the examiner explore the actual fitted model rather than seeing an unexplained label.')
p('How the explanation is computed','Heading2');p('First, the model scores the complete input panel. For each observed lab value, a copy of that panel replaces only that feature with its training median. The original winning category is held fixed when comparing the scores. The score difference is displayed in percentage points. A positive difference means the observed value supports that score relative to the selected reference. Missing fields are excluded from this explanation.')
p('Interactive comparison','Heading2');p('The user can pin a result, change values, and analyze again. DNA reports the changed inputs, the new winning category and the change in the pinned category score. Comparisons use the same fitted model. Results can be exported as JSON, including inputs, class scores, imputation disclosures and sensitivity values.')
p('Concrete example','Heading2');p('Load a held-out sample and run the model. Pin the output, alter ALT, and run again. The comparison panel shows whether the class changes and how much the original category score moves. A lack of movement is also informative: the ensemble may not cross relevant split thresholds for that change.')
p('What is novel in this project','Heading2');p('The feature combines transparent missing-value handling, local input sensitivity and interactive comparison inside one student-facing application. It is a software contribution for this project, not a claim that one-at-a-time sensitivity analysis or Random Forest is a new research method.')
p('Interpretation limits','Heading2');p('The explanation is not SHAP and does not provide additive feature attribution. Correlated tests can make one-at-a-time changes unrealistic, and medians are dataset references rather than healthy clinical targets. The effects cannot justify treatment recommendations. The top-score review flag at 65% is illustrative and has not been selected for clinical sensitivity or calibrated risk.')
p('Feature verification','Heading2');p('Automated checks compare the displayed sensitivity calculation against direct pipeline inference on the same modified inputs. Separate tests check invalid input rejection, missing-value disclosures, and agreement between endpoint predictions and every saved test prediction.')
page('Limitations and future expansion')
p('Current limitations','Heading2');p('The dataset is small and heavily dominated by blood donors. Rare categories are represented by very few records, limiting both training and evaluation. The model has no external hospital validation and no probability calibration. Random splitting cannot establish performance across different populations, instruments, or data collection procedures.')
p('A category is not a confirmed diagnosis','Heading2');p('DNA learns the categories in the source file. A donor prediction does not rule out disease, and a disease-category prediction does not establish the clinical condition. The input-range warning checks individual values only; it cannot establish whether an entire panel is realistic or whether its units match the research data.')
fig('class_performance.png',350,175,'Figure 2. Per-class precision and recall expose weaknesses hidden by overall accuracy.')
p('Adding more diseases later','Heading2');p('Keep each disease dataset and model separate. A new module needs a source citation and license, documented input units, explicit target definitions, preprocessing fitted within training folds, and its own test evaluation. Only then should it be exposed in the DNA interface. The module registry and namespaced HCV artifacts provide a starting structure; HCV is the only implemented training workflow today.')
p('Why unrelated datasets should not simply be joined','Heading2');p('Kidney, thyroid and liver datasets have different tests and populations. Combining rows with zero-filled absent tests may reveal the data source rather than disease. Separate modules support independent evaluation and overlapping disease flags.')
p('Next study improvements','Heading2');p('Before adding modules, examine HCV errors and calibration using training-only validation. Avoid tuning on the test set. Seek more representative external data.')
page('Conclusion and references')
p('Conclusion','Heading2');p(f'DNA implements a working HCV laboratory classification system using Random Forest. The measured test accuracy is {pct(m["accuracy"])}, while macro F1 is {m["macro_f1"]:.3f} and balanced accuracy is {pct(m["balanced_accuracy"])}. Together these measures show that the system performs strongly on the dominant donor category but remains limited on rare categories.')
p('The project demonstrates data preparation, leakage-free preprocessing, multiclass evaluation, saved-model inference and a branded interface. Explain and Explore makes model behavior inspectable without treating model responses as clinical rules. Future disease coverage should proceed through separately validated modules after the current workflow and its limitations are understood.')
p('References','Heading2')
refs=[('[1] Lichtinghagen, R., Klawonn, F., and Hoffmann, G. (2020). HCV data. UCI Machine Learning Repository. CC BY 4.0.','https://doi.org/10.24432/C5D612'),('[2] Breiman, L. (2001). Random Forests. Machine Learning, 45, 5-32.','https://doi.org/10.1023/A:1010933404324'),('[3] scikit-learn. RandomForestClassifier API documentation.','https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html'),('[4] Hoffmann, G., Bietenbeck, A., Lichtinghagen, R., and Klawonn, F. (2018). Using machine learning techniques to generate laboratory diagnostic pathways - a case study. Journal of Laboratory and Precision Medicine.','https://doi.org/10.21037/jlpm.2018.06.01')]
for title,url in refs:p(title);p(f'<a href="{url}" color="#197268">{url}</a>','Note')
p('Reproduction evidence','Heading2');p('All reported model results come from artifacts/hcv/metrics.json and test_predictions.csv. The source data is data/hcv/hcvdat0.csv. The source authors and UCI retain the dataset attribution; Team DNA provides the project implementation.','Note')
p('The original dataset publication [4] provides background on laboratory diagnostic pathways. This report does not substitute its results for the evaluation of DNA.','Note')
p('Source file SHA-256: '+m['sha256'],'Note')
def footer(canvas,doc):
    canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#697f72'));canvas.drawString(72,31,'DNA | HCV laboratory classification | Academic project');canvas.drawRightString(540,31,str(doc.page))
SimpleDocTemplate(str(OUT/'DNA_HCV_Report.pdf'),pagesize=letter,leftMargin=72,rightMargin=72,topMargin=48,bottomMargin=48,title='DNA Disease Diagnosis Using Random Forest',author='Team DNA').build(story,onFirstPage=footer,onLaterPages=footer)
web.append('</section>');css='body{font:16px/1.6 Georgia,serif;background:#eff3ef;color:#203c30;margin:0}section{box-sizing:border-box;max-width:850px;background:white;margin:24px auto;padding:50px 60px}h1,h2,h3{font-family:Arial}h1{font-size:34px}table{border-collapse:collapse;width:100%;font:14px/1.5 Arial;margin:18px 0}td,th{padding:9px;border-bottom:1px solid #dce5de;text-align:left;vertical-align:top}th{background:#eaf1ec}img{display:block;max-width:100%;max-height:430px;margin:20px auto}a{overflow-wrap:anywhere;color:#197268}@media print{section{page-break-after:always;margin:0;padding:0}}'
(OUT/'DNA_HCV_Report.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><title>DNA HCV project report</title><style>'+css+'</style><body>'+''.join(web)+'</body></html>',encoding='utf-8')
print('Created DNA_HCV_Report.pdf and editable HTML')

